pipeline {
    agent any
    parameters {
        string(
            name: "TEXT",
            description: "The text which you want to convert into QR-code.",
            defaultValue: "http://localhost:8080/",
        )
        string(
            name: "FILE_NAME",
            description: "The file name of output QR code: ${FILE_NAME}.png.",
            defaultValue: "output",
        )
    }
    stages {
        stage("git-clone") {
            steps {
                sh """
                    if [ -d ./qrcode-script ]; then
                        pwd
                        cd ./qrcode-script
                        git checkout main
                        git pull origin/main main
                    else
                        git clone https://github.com/takahiroaoki/qrcode-script.git
                        git checkout main
                    fi
                """
            }
        }
        stage("build") {
            steps {
                sh """
                    cd ./qrcode-script
                    docker-compose run --rm -e TEXT="${TEXT}" -e FILE_NAME="${FILE_NAME}" qrcode
                """
            }
        }
    }
}